-- seeds/03_ingredients.sql

-- Ingredients table seeds here (Example)
INSERT INTO ingredients (name, quantity, category, user_id) VALUES ('tomato', 3, 'vegetables', 1),
('tomato', 4, 'vegetables', 2),
('tomato', 1, 'vegetables', 3),
('tomato', 2, 'vegetables', 4),
('tomato', 3, 'vegetables', 5),
('avocado', 1, 'vegetables', 1),
('avocado', 3, 'vegetables', 2),
('avocado', 2, 'vegetables', 3),
('avocado', 1, 'vegetables', 4),
('avocado', 4, 'vegetables', 5),
('apple', 5, 'fruit', 1),
('apple', 3, 'fruit', 2),
('apple', 2, 'fruit', 3),
('apple', 1, 'fruit', 4),
('apple', 1, 'fruit', 5),
('broccoli', 1, 'vegetables', 1),
('broccoli', 2, 'vegetables', 2),
('broccoli', 1, 'vegetables', 3),
('broccoli', 2, 'vegetables', 4),
('broccoli', 1, 'vegetables', 5),
('cheddar cheese', 1, 'cheese', 1),
('cheddar cheese', 1, 'cheese', 2),
('cheddar cheese', 1, 'cheese', 3),
('cheddar cheese', 1, 'cheese', 4),
('cheddar cheese', 2, 'cheese', 5),
('cucumber', 2, 'vegetables', 1),
('cucumber', 1, 'vegetables', 2),
('cucumber', 2, 'vegetables', 3),
('cucumber', 1, 'vegetables', 4),
('cucumber', 1, 'vegetables', 5),
('mango', 3, 'fruit', 1),
('mango', 2, 'fruit', 2),
('mango', 1, 'fruit', 3),
('mango', 2, 'fruit', 4),
('mango', 3, 'fruit', 5),
('mushrooms', 3, 'vegetables', 1),
('mushrooms', 4, 'vegetables', 2),
('mushrooms', 1, 'vegetables', 3),
('mushrooms', 2, 'vegetables', 4),
('mushrooms', 3, 'vegetables', 5),
('orange', 3, 'fruit', 1),
('orange', 4, 'fruit', 2),
('orange', 1, 'fruit', 3),
('orange', 2, 'fruit', 4),
('orange', 3, 'fruit', 5),
('potato', 5, 'vegetables', 1),
('potato', 7, 'vegetables', 2),
('potato', 9, 'vegetables', 3),
('potato', 10, 'vegetables', 4),
('potato', 4, 'vegetables', 5),
('chicken', 1, 'protein', 1),
('chicken', 1, 'protein', 2),
('chicken', 3, 'protein', 3),
('chicken', 2, 'protein', 4),
('chicken', 3, 'protein', 5),
('shrimp', 1, 'vprotein', 1),
('shrimp', 1, 'protein', 2),
('shrimp', 1, 'protein', 3),
('shrimp', 1, 'protein', 4),
('shrimp', 1, 'protein', 5),
('rice', 1, 'Pasta, rice, and cereals', 1),
('rice', 1, 'Pasta, rice, and cereals', 2),
('rice', 1, 'Pasta, rice, and cereals', 3),
('rice', 1, 'Pasta, rice, and cereals', 4),
('rice', 1, 'Pasta, rice, and cereals', 5),
('quinoa', 1, 'Pasta, rice, and cereals', 1),
('quinoa', 1, 'Pasta, rice, and cereals', 2),
('quinoa', 1, 'Pasta, rice, and cereals', 3),
('quinoa', 1, 'Pasta, rice, and cereals', 4),
('quinoa', 1, 'Pasta, rice, and cereals', 5)